name       : libice
version    : 1.0.9
release    : 8
source     :
    - http://xorg.freedesktop.org/releases/individual/lib/libICE-1.0.9.tar.bz2 : 8f7032f2c1c64352b5423f6b48a8ebdc339cc63064af34d66a6c9aa79759e202
license    :
    - MIT
summary    : Inter-Client Exchange Library
component  : xorg.library
description: |
    This package provides the main interface to the X11 Inter-Client Exchange
    library, which allows for communication of data between X clients.
builddeps  :
    - pkgconfig(xtrans)
    - pkgconfig(xproto)
emul32     : yes
optimize   : speed
setup      : |
    %configure --prefix=/usr \
               --disable-static
build      : |
    %make
install    : |
    %make_install
