name        : libice
version     : 1.0.9
release     : 5
source      :
    - http://xorg.freedesktop.org/releases/individual/lib/libICE-1.0.9.tar.bz2 : 8f7032f2c1c64352b5423f6b48a8ebdc339cc63064af34d66a6c9aa79759e202
license     :
    - MIT
summary     : Inter-Client Exchange Library
component   : xorg.library
builddeps   :
    - pkgconfig(xtrans)
    - pkgconfig(xproto)
    - glibc-32bit-devel
    - libgcc-32bit
emul32      : yes
optimize    : speed
description : |
    This package provides the main interface to the X11 Inter-Client Exchange library, which allows for communication of data between X clients.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
