name       : libice
version    : 1.1.0
release    : 13
source     :
    - https://www.x.org/releases/individual/lib/libICE-1.1.0.tar.xz : 02d2fc40d81180bd4aae73e8356acfa2a7671e8e8b472e6a7bfa825235ab225b
license    :
    - MIT
summary    : Inter-Client Exchange Library
component  : xorg.library
description: |
    This package provides the main interface to the X11 Inter-Client Exchange library, which allows for communication of data between X clients.
builddeps  :
    - pkgconfig(xtrans)
    - pkgconfig(xproto)
emul32     : yes
optimize   : speed
patterns   :
    - /usr/share
setup      : |
    %configure --prefix=/usr \
               --disable-static
build      : |
    %make
install    : |
    %make_install
